languageCode = "en-us"
title = "blog of kittenm4ster"
baseURL = "https://kittenm4ster.neocities.org/blog/"
author = "kittenm4ster"
canonifyurls = true
preserveTaxonomyNames = true

theme = "paperback"

[taxonomies]
tag = "tags"
